name = "MultipleSourceOptimalGauss"
uuid = "195e37f8-a172-4399-9420-c91f8b1ab648"
authors = ["Stephan Scholz"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
